sudo: required 
services:
  - docker
# realistically can tag as anything because we are just testing but otherwise for real conventions
before_install:
  - docker build -t chreart723/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true chreart723/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-app-eb-env"
  env: "docker-react-app-eb-env-env"
  bucket_name: "elasticbeanstalk-us-east-1-578002456900"
  bucket_path: "docker-react-app-eb-env"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"